### ISSUE TITLE
Is it possible to parameterise the radius?

### ISSUE THREAD

**Issue by systemsolve** [jmargenberg/covid-5km-overlap-finder#7]
Currently the radius seems to be a const in Maps.jsx. Is it possible to make it a parameter to the URL?

I tried hacking it in Chrome devtools but as a const, I don't think it was effective.

**Comment by jmargenberg** [comment]
Hey @systemsolve, sure thing,

I've added a limited dropdown for the planned lockdown radius increments in Victoria (5, 10, 15 and 25km) so that I don't have to worry about staying as up to date with these constantly changing rules.

I had been hesitant to add full control of the radius to keep the site's UI as clean and uncluttered as possible but I like your suggestion of using the URL parameters so I have also updated the site to use the `radius` query param in the URL to fully control the displayed radius.

Thanks for the suggestion 👍
